name: Hello world
on:
  pull_request:
    types: ["opened", "reopened", "synchronize"]
  # schedule:
    # - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.18.0
        with:
            java-version: 18
            maven-version: 3.9.9

      - name: Execute E2E testes
        run: mvn clean install
